### ISSUE TITLE
export default class ... breaks transpiler

### ISSUE THREAD

**Issue by espretto** [AMorgaut/babel-plugin-transform-class#24]
Hello,

thank you for making this great alternative for babel's class-transform. the spec-compliant version seems rather heavy, especially after [d. walsh on prototypes](https://davidwalsh.name/javascript-objects-deconstruction) (link in the readme?).

When I try to export and declare a class on the same line, I get the following error:
```
Error transforming <path>/src/dom/treewalker.js with 'babel' plugin: <path>/src/dom/treewalker.js: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
Error: <path>/src/dom/treewalker.js: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
    at NodePath.insertAfter (<path>/node_modules/babel-traverse/lib/path/modification.js:175:13)
    at NodePath.replaceWithMultiple (<path>/node_modules/babel-traverse/lib/path/replacement.js:82:8)
    at PluginPass.exit (<path>/node_modules/babel-plugin-transform-class/lib/index.js:20:14)
    at newFn (<path>/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (<path>/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (<path>/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (<path>/node_modules/babel-traverse/lib/path/context.js:117:8)
    at TraversalContext.visitQueue (<path>/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (<path>/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (<path>/node_modules/babel-traverse/lib/context.js:192:19)
```

Here goes `/src/dom/treewalker.js`
```js
export default class TreeWalker {
  // empty test
}
```

My solution for now is to put the export on a seperate line.

**Comment by AMorgaut** [comment]
Thank you for your feedback

I usually use dedicated lines for exports

But yes this should be supported, I'll look into it

**Comment by AMorgaut** [comment]
Did some try
@espretto 
Which transform plugin did you use for the es6 module support?

**Comment by espretto** [comment]
I'm using a subset of the `@babel/preset-env`, here goes my .babelrc:
```
{
  "plugins": [
    "@babel/plugin-transform-flow-strip-types",
    
    "transform-class",

    "@babel/plugin-transform-arrow-functions",
    "@babel/plugin-transform-block-scoped-functions",
    "@babel/plugin-transform-block-scoping",
    ["@babel/plugin-transform-computed-properties", { "loose": false }],
    "@babel/plugin-transform-destructuring",
    "@babel/plugin-transform-duplicate-keys",
    "@babel/plugin-transform-literals",
    "@babel/plugin-transform-parameters",
    "@babel/plugin-transform-shorthand-properties",
    "@babel/plugin-transform-spread",
    "@babel/plugin-transform-template-literals"
  ],
  "parserOpts": {
    "plugins": ["flow"]
  }
}
```
I can't find the module support though. it just seems to work with both webpack's babel-loader and rollup-babel-plugin.

**Comment by AMorgaut** [comment]
Thanks
I think I found the solution
If you are ok, I'll publish it in a feature branch so you can confirm it is working for you, and add you as a reviewer of the Pull Request

**Comment by AMorgaut** [comment]
So current state is working, but will still try to make it better

Instead of failing it now transforms

```js
export default class TreeWalker {
  // empty test
}
```

Into

```js
function TreeWalker() {
  // empty test
}
export default TreeWalker
```

and 

```js
export class TreeWalker {
  // empty test
}
```

Into

```js
function TreeWalker() {
  // empty test
}
export { TreeWalker }
```

----------------------------------------------------------------------------------

Note that I realize it is kind of a workaround.
I'm a bit concerned because my transform plugin is meant to work "as-is" and provide

```js
export default function TreeWalker() {
  // empty test
}

```
and

```js
export function TreeWalker() {
  // empty test
}
```

I'll spend a little more time to get what's going wrong
